## Day objectives

- Comprehensions
- Iterators and Generators
- Data Science Libraries

- Comprehension
    - It is a process creating new sequence from existing sequence
- Advantages
    - Less code and easier to understand
- Types of Comprehensions
    - List comprehension
    - Dictionary comprehension
    - Set comprehension
    - Generator comprehension

## List comprehension

In [1]:
li = [1,2,3,4,5,6,7]
li1 = []
for i in li:
    if(i%2!=0):
        li1.append(i)
li1

[1, 3, 5, 7]

In [2]:
li = [1,2,3,4,5,6,7]
t = [i for i in li if i%2!=0]
t

[1, 3, 5, 7]

In [3]:
a = [i**3 for i in range(9)]
a

[0, 1, 8, 27, 64, 125, 216, 343, 512]

In [4]:
b = [i if i%2 == 0 else 'Odd' for i in a]
b

[0, 'Odd', 8, 'Odd', 64, 'Odd', 216, 'Odd', 512]

In [5]:
a = ['Welcome to python programming','this session is about comprehensions']
li = []
for i in a:
    for j in i.split():
        li.append(j)
li

['Welcome',
 'to',
 'python',
 'programming',
 'this',
 'session',
 'is',
 'about',
 'comprehensions']

In [6]:
x = [j for i in a for j in i.split()]
x

['Welcome',
 'to',
 'python',
 'programming',
 'this',
 'session',
 'is',
 'about',
 'comprehensions']

In [7]:
a = [[i*j for i in range(1,11)] for j in range(1,11)]
a

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
 [4, 8, 12, 16, 20, 24, 28, 32, 36, 40],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
 [6, 12, 18, 24, 30, 36, 42, 48, 54, 60],
 [7, 14, 21, 28, 35, 42, 49, 56, 63, 70],
 [8, 16, 24, 32, 40, 48, 56, 64, 72, 80],
 [9, 18, 27, 36, 45, 54, 63, 72, 81, 90],
 [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]]

## Dictionary Comprehension

In [8]:
d = {i:i**3 for i in range(6)}
d

{0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125}

## Set comprehension

In [9]:
li = [1,3,4,5,78,90,5,9,3]
s = set()
for i in li:
    if i%2 != 0:
        s.add(i**3)
s

{1, 27, 125, 729}

In [10]:
s = {i**3 for i in li if i%2!=0}
s

{1, 27, 125, 729}

## Generator comprehension

In [11]:
li = [1,3,4,5]
c = (i**2 for i in li)
print(c)
for i in c:
    print(i,end=' ')

<generator object <genexpr> at 0x0000028E4AFD36D0>
1 9 16 25 

## Iterators and Generators

- Iterators
    - It will contain number elements and we can access element as per requirement
    - iter and next are the cocepts we use in iterator

In [12]:
s = 'Covid'
for i in s:
    print(i)

C
o
v
i
d


In [13]:
s = 'Covid'
s_iter = iter(s)
next(s_iter)


'C'

In [14]:
next(s_iter)

'o'

In [15]:
next(s_iter)

'v'

In [16]:
print('hello')

hello


In [17]:
next(s_iter)

'i'

- Generator
    - Generators is also like a function but in place of return we will use yield
    - Generators will be used in combination of iterations

In [21]:
def add(a,b):
    print('hii')
    return a+b
    return a-b
    print('Good evening')
    
add(6,12)

hii


18

In [22]:
def generator_example():
    yield 'n'
    yield 2
    yield 3
    yield 4
    
for value in generator_example():
    print(value)

n
2
3
4


## Data Science Libraries

- Data Science
    - A field of science that study the data and analyse the data to get perfect valuable insights by applying different techniqs.
    - Mainly we are using DS for Machine Learning and for AI

- Libraries
    - Numpy
        - Numerical Python
        - We are using this for Scientific caluculation
        - Log,Trig functions, FT, exponentials..etc
    - Pandas
        - Data Analysis, Data manupulation, Data cleaning
    - Matplotlib
        - Data Visulization

## Numpy

In [23]:
import numpy as np


In [24]:
np.__version__

'1.18.5'

In [27]:
ar = np.array([[1,2,3],[5,6,7]])
ar

array([[1, 2, 3],
       [5, 6, 7]])

In [29]:
## predefined functions

print(ar.dtype)

int32


In [30]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [31]:
print(b.shape)

(2, 2)


In [32]:
print(ar.shape)

(2, 3)


In [33]:
print(b.ndim)

2


In [34]:
print(b.size)

4


In [35]:
print(ar.size)

6


## range()

In [40]:
a = np.array(range(10))
print(a)
print('--------------------')
b = np.array(range(1,10))
print(b)
print('------------------')
c = np.array(range(1,20,2))
print(c)

[0 1 2 3 4 5 6 7 8 9]
--------------------
[1 2 3 4 5 6 7 8 9]
------------------
[ 1  3  5  7  9 11 13 15 17 19]


## arange()

In [42]:
a = np.arange(10)
print(a)
b = np.arange(1,10)
print(b)
c = np.arange(1,30,3)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 1  4  7 10 13 16 19 22 25 28]


## reshape()

In [43]:
x = np.arange(10)
print(x.reshape(5,2)) ## reshape(row_size,column_size)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [44]:
x.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
x.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
a = np.ones((3,3), dtype = int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
b = np.zeros((2,3), dtype = int)
b

array([[0, 0, 0],
       [0, 0, 0]])

In [50]:
d = np.full((2,2),7)
d

array([[7, 7],
       [7, 7]])

In [51]:
t = np.arange(9).reshape(3,3)
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
np.diag(t)

array([0, 4, 8])

In [56]:
r = np.random.randint(10)
r

7

In [58]:
r1 = np.random.randint(3,8)
r1

4

In [60]:
r2 = np.random.randint(1,20,10)
r2

array([18, 15, 13, 16, 11, 11,  7, 16,  4,  4])

In [63]:
r3 = np.random.random(6)
r3
## 0 to 1

array([0.42542702, 0.21523832, 0.09811002, 0.60505105, 0.03567587,
       0.73192504])

In [62]:
r4 = np.random.randn(4)
r4

array([-1.51948266, -3.33170006,  0.5330699 , -0.12477277])

In [64]:
s = np.random.randint(1,20,12).reshape(3,4)
s

array([[16, 15, 10, 16],
       [ 2,  6,  4,  8],
       [ 1, 17,  8,  9]])

## Slicing

In [65]:
a = np.random.randint(1,30,(10,3))
a

array([[14,  5, 21],
       [23, 25, 13],
       [10, 20,  5],
       [ 1,  4, 27],
       [10, 16, 21],
       [ 3, 15, 21],
       [12, 10, 20],
       [13, 12, 10],
       [24,  9, 25],
       [17,  1, 12]])

In [66]:
## [start:end:step]
a[1:5]

array([[23, 25, 13],
       [10, 20,  5],
       [ 1,  4, 27],
       [10, 16, 21]])

In [67]:
a[5:]

array([[ 3, 15, 21],
       [12, 10, 20],
       [13, 12, 10],
       [24,  9, 25],
       [17,  1, 12]])

In [68]:
li = [1,2,3,4,5]
li[1:5]

[2, 3, 4, 5]

In [69]:
li[3:]

[4, 5]

In [71]:
a[2:,:2]

array([[10, 20],
       [ 1,  4],
       [10, 16],
       [ 3, 15],
       [12, 10],
       [13, 12],
       [24,  9],
       [17,  1]])

In [72]:
print(a>5)

[[ True False  True]
 [ True  True  True]
 [ True  True False]
 [False False  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]]


In [73]:
a[a>5]

array([14, 21, 23, 25, 13, 10, 20, 27, 10, 16, 21, 15, 21, 12, 10, 20, 13,
       12, 10, 24,  9, 25, 17, 12])

In [74]:
a[a>5].sum()

400

In [75]:
a.max()

27

In [76]:
a.min()

1

In [77]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [79]:
print(a+b)

[[10 12 14]
 [16 18 20]
 [22 24 26]]


In [80]:
print(a-b)

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [81]:
print(a*b)

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


In [82]:
print(a/b)

[[0.         0.09090909 0.16666667]
 [0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444]]


In [83]:
print(a%b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [85]:
print(np.mean(a))

4.0


In [86]:
print(np.std(a))

2.581988897471611


In [88]:
print(np.median(a))

4.0


In [90]:
print(b.dot(a))

[[105 138 171]
 [132 174 216]
 [159 210 261]]


In [91]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
print(a+3)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [93]:
print(a-2)

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [94]:
print(a*4)

[[ 0  4  8]
 [12 16 20]
 [24 28 32]]


In [95]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [96]:
np.exp((3,4,5))

array([ 20.08553692,  54.59815003, 148.4131591 ])

In [103]:
np.log10(2)

0.3010299956639812

In [99]:
np.sin(0)


0.0

In [100]:
np.cos(0)

1.0

In [101]:
np.tan(0)

0.0

In [ ]:
cot == cos/sin
sec = 1/cos
csec = 1/sin

In [102]:
print(dir(np),end=' ')

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes